name: Deploy storybook
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

        # Build and Deploy storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.M3NTORSHIP_UI_LIBIRARY_CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true #

  output-storybook-url:
    if: ${{ github.event_name == 'pull_request' }}
    needs: chromatic-deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout pull request HEAD commit instead of merge commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit data action
        uses: rlespinasse/git-commit-data-action@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### 🚀🚀 Storybook deployed successfully 🚀🚀 🎉 🎉
            See the latest storybook changes for this PR [here](https://${{ env.GIT_COMMIT_SHORT_SHA }}--${{ secrets.CHROMATIC_APP_ID }}.chromatic.com)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
